// Script para convertir subvenciones.ts a archivos JSON individuales
import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const subvenciones = [
  {
    id: 'galicia-autonomos-contratacion-tr349f',
    codigo: 'TR349F',
    nombre: 'Programa de ayudas a personas trabajadoras autónomas por contratación indefinida',
    comunidad: 'galicia',
    categoria: 'contratacion',
    organismo: 'Xunta de Galicia - Consellería de Emprego',
    estado: 'abierta',
    plazoInicio: '11 de febrero de 2026',
    plazoFin: '30 de septiembre de 2026',
    plazoTexto: 'Desde el 11 de febrero al 30 de septiembre de 2026',
    objeto: 'Incentivar la contratación indefinida del 1º, 2º y 3º trabajador por parte de personas trabajadoras autónomas',
    beneficiarios: 'Personas trabajadoras autónomas dadas de alta en el RETA con domicilio fiscal en Galicia que realicen contrataciones indefinidas.',
    imagen: '/images/subvenciones/contratacion-autonomos.png',
    destacada: true,
  },
  {
    id: 'galicia-emprega-tr342c',
    codigo: 'TR342C',
    nombre: 'Plan Galicia Emprega 2026 - Ayuda a la Contratación',
    comunidad: 'galicia',
    categoria: 'contratacion',
    organismo: 'Xunta de Galicia - Consellería de Emprego',
    estado: 'proxima',
    plazoTexto: 'Convocatoria prevista a inicios de 2026',
    objeto: 'Fomentar la contratación de personas desempleadas con especiales dificultades de inserción laboral en Galicia',
    beneficiarios: 'Empresas y autónomos con centro de trabajo en Galicia que realicen contrataciones indefinidas de personas desempleadas.',
    imagen: '/images/subvenciones/galicia-emprega.png',
  },
  {
    id: 'galicia-suma-talento-tr301p',
    codigo: 'TR301P',
    nombre: 'Galicia Suma Talento: Plan formación empresas 2026',
    comunidad: 'galicia',
    categoria: 'contratacion',
    organismo: 'Xunta de Galicia',
    estado: 'abierta',
    plazoInicio: '14 de enero de 2026',
    plazoFin: '1 de diciembre de 2026',
    plazoTexto: 'Desde el 14 de enero hasta el 1 de diciembre de 2026',
    objeto: 'Financiar planes de formación empresarial con compromiso de contratación posterior',
    beneficiarios: 'Empresas con centro de trabajo en Galicia que se comprometan a contratar a las personas formadas.',
    imagen: '/images/subvenciones/galicia-emprega.png',
  },
  {
    id: 'galicia-bonos-talento-tr302d',
    codigo: 'TR302D',
    nombre: 'Bonos Talento Empresa 2026-2027',
    comunidad: 'galicia',
    categoria: 'contratacion',
    organismo: 'Xunta de Galicia',
    estado: 'proxima',
    plazoTexto: 'Convocatoria prevista para mediados de 2026',
    objeto: 'Financiar formación no formal en materias específicas para trabajadores de empresas gallegas',
    beneficiarios: 'Empresas con centro de trabajo en Galicia.',
    imagen: '/images/subvenciones/galicia-emprega.png',
  },
  {
    id: 'galicia-practicas-jovenes-tr353c',
    codigo: 'TR353C',
    nombre: 'Práctica Profesional Jóvenes 2026',
    comunidad: 'galicia',
    categoria: 'contratacion',
    organismo: 'Xunta de Galicia',
    estado: 'proxima',
    plazoTexto: 'Convocatoria prevista para mediados de 2026',
    objeto: 'Incentivar los contratos para prácticas profesionales de jóvenes titulados',
    beneficiarios: 'Empresas que contraten jóvenes titulados para prácticas profesionales.',
    imagen: '/images/subvenciones/emprendimiento.png',
  },
  {
    id: 'galicia-transformacion-digital-comercio-co300c',
    codigo: 'CO300C',
    nombre: 'Subvenciones para la transformación digital, innovación y modernización del sector comercial y artesanal',
    comunidad: 'galicia',
    categoria: 'digitalizacion',
    organismo: 'Xunta de Galicia - Consellería de Economía e Industria',
    estado: 'abierta',
    plazoInicio: '16 de enero de 2026',
    plazoFin: '16 de febrero de 2026',
    plazoTexto: 'Desde el 16 de enero al 16 de febrero de 2026',
    tipoAyuda: 'En concurrencia no competitiva. Régimen de minimis.',
    objeto: 'Apoyo para el impulso de la innovación, digitalización y sostenibilidad del comercio local y artesanal',
    beneficiarios: 'Comerciantes minoristas con tienda física y talleres artesanos inscritos en el Registro de Artesanía de Galicia.',
    beneficiariosDetalle: [
      'COMERCIANTES MINORISTAS: Que desarrollen su actividad comercial en Galicia, sean PYME con 10 o menos empleados, y tengan superficie de venta igual o inferior a 300 m².',
      'TALLERES ARTESANOS: Inscritos en el Registro General de Artesanía de Galicia.'
    ],
    actuacionesSubvencionables: [
      {
        linea: 'Línea de digitalización comercial e innovación',
        porcentaje: '80%',
        items: [
          { nombre: 'Página web con o sin venta en línea', importeMax: '1.200 €' },
          { nombre: 'Sistema TPV, impresora, lector código barras, báscula', importeMax: '1.200 €' },
          { nombre: 'Software de gestión comercial', importeMax: '5.000 €' },
          { nombre: 'Posicionamiento digital (SEO, SEM, ADS)', importeMax: '2.500 €' },
          { nombre: 'Gestor de redes sociales', importeMax: '2.000 €' },
          { nombre: 'Etiquetado electrónico', importeMax: '2.500 €' },
          { nombre: 'Sistemas click and collect', importeMax: '2.500 €' },
          { nombre: 'Soluciones de ciberseguridad', importeMax: '2.000 €' },
          { nombre: 'Chatbots y asistentes virtuales', importeMax: '1.000 €' },
          { nombre: 'Apps móviles y realidad virtual/aumentada', importeMax: '2.500 €' },
          { nombre: 'Pantallas y escaparates virtuales', importeMax: '5.000 €' },
        ]
      },
      {
        linea: 'Línea de modernización comercial',
        porcentaje: '80%',
        items: [
          { nombre: 'Obras de reforma y mobiliario', importeMax: '5.250 €' },
          { nombre: 'Proyecto de interiorismo', importeMax: '2.000 €' },
          { nombre: 'Puertas automáticas', importeMax: '2.000 €' },
          { nombre: 'Iluminación eficiente', importeMax: '2.000 €' },
          { nombre: 'Climatización eficiente', importeMax: '4.000 €' },
          { nombre: 'Mejora de fachada y rótulos', importeMax: '2.000 €' },
          { nombre: 'Equipamiento comercial', importeMax: '5.000 €' },
        ]
      },
      {
        linea: 'Línea de sostenibilidad ambiental',
        porcentaje: '80%',
        items: [
          { nombre: 'Embalajes sostenibles (cartón reciclado, bolsas de papel/tela)', importeMax: '2.500 €' },
        ]
      }
    ],
    plazoEjecucion: 'Desde el 25 de octubre de 2025 hasta el 13 de noviembre de 2026',
    imagen: '/images/subvenciones/contratacion-autonomos.png',
    destacada: true,
  },
  {
    id: 'galicia-inteligencia-artificial-ig408m',
    codigo: 'IG408M',
    nombre: 'Ayudas Inteligencia Artificial IGAPE - IA360',
    comunidad: 'galicia',
    categoria: 'digitalizacion',
    organismo: 'IGAPE - Xunta de Galicia',
    estado: 'abierta',
    plazoInicio: '17 de enero de 2026',
    plazoFin: '17 de marzo de 2026',
    plazoTexto: 'Desde el 17 de enero al 17 de marzo de 2026',
    objeto: 'Apoyar el desarrollo e implantación de soluciones de Inteligencia Artificial en empresas gallegas',
    beneficiarios: 'Pymes con sede social o centro de trabajo en Galicia.',
    imagen: '/images/subvenciones/innovacion-igape.png',
  },
  {
    id: 'galicia-pyme-cibersegura',
    codigo: 'CIBER26',
    nombre: 'PYME Cibersegura 2026',
    comunidad: 'galicia',
    categoria: 'digitalizacion',
    organismo: 'Xunta de Galicia',
    estado: 'proxima',
    plazoTexto: 'Convocatoria prevista para el segundo trimestre de 2026',
    objeto: 'Mejorar la ciberseguridad de las pymes gallegas mediante auditorías y soluciones de protección',
    beneficiarios: 'Pymes con sede social o centro de trabajo en Galicia.',
    imagen: '/images/subvenciones/innovacion-igape.png',
  },
  {
    id: 'galicia-pyme-digital',
    codigo: 'DIGIT26',
    nombre: 'PYME Digital 2026',
    comunidad: 'galicia',
    categoria: 'digitalizacion',
    organismo: 'Xunta de Galicia',
    estado: 'proxima',
    plazoTexto: 'Convocatoria prevista para el segundo trimestre de 2026',
    objeto: 'Impulsar la digitalización y el marketing digital de las pymes gallegas',
    beneficiarios: 'Pymes con sede social o centro de trabajo en Galicia.',
    imagen: '/images/subvenciones/innovacion-igape.png',
  },
  {
    id: 'galicia-promocion-autonomo-tr341d',
    codigo: 'TR341D',
    nombre: 'Promoción del empleo autónomo',
    comunidad: 'galicia',
    categoria: 'emprendedores',
    organismo: 'Xunta de Galicia - Consellería de Emprego',
    estado: 'abierta',
    plazoInicio: '11 de febrero de 2026',
    plazoFin: '30 de septiembre de 2026',
    plazoTexto: 'Desde el 11 de febrero al 30 de septiembre de 2026',
    objeto: 'Apoyar a las personas que se establezcan como trabajadoras autónomas en Galicia',
    beneficiarios: 'Personas que se den de alta como autónomas y creen su propio puesto de trabajo.',
    imagen: '/images/subvenciones/contratacion-autonomos.png',
  },
  {
    id: 'galicia-startup-ig408g',
    codigo: 'IG408G',
    nombre: 'Start up Galicia',
    comunidad: 'galicia',
    categoria: 'emprendedores',
    organismo: 'IGAPE - Xunta de Galicia',
    estado: 'abierta',
    plazoInicio: '28 de enero de 2026',
    plazoFin: '30 de septiembre de 2026',
    plazoTexto: 'Desde el 28 de enero al 30 de septiembre de 2026',
    objeto: 'Financiar gastos operativos de startups y empresas emergentes gallegas',
    beneficiarios: 'Startups y empresas emergentes con sede en Galicia.',
    imagen: '/images/subvenciones/innovacion-igape.png',
  },
  {
    id: 'galicia-emprendimiento-tr880a',
    codigo: 'TR880A',
    nombre: 'Emprendimiento 2026',
    comunidad: 'galicia',
    categoria: 'emprendedores',
    organismo: 'Xunta de Galicia',
    estado: 'abierta',
    plazoInicio: '31 de enero de 2026',
    plazoFin: '2 de marzo de 2026',
    plazoTexto: 'Desde el 31 de enero al 2 de marzo de 2026',
    objeto: 'Apoyar inversiones en maquinaria, reformas y software para nuevos emprendedores',
    beneficiarios: 'Nuevos emprendedores y empresas de reciente creación en Galicia.',
    imagen: '/images/subvenciones/emprendimiento.png',
    destacada: true,
  },
  {
    id: 'galicia-emprendimiento-plus-tr880b',
    codigo: 'TR880B',
    nombre: 'Emprendimiento Plus 2026',
    comunidad: 'galicia',
    categoria: 'emprendedores',
    organismo: 'Xunta de Galicia',
    estado: 'proxima',
    plazoTexto: 'Convocatoria prevista a inicios de 2026',
    objeto: 'Apoyar la contratación y el equipamiento de nuevos emprendedores',
    beneficiarios: 'Nuevos emprendedores y empresas de reciente creación en Galicia.',
    imagen: '/images/subvenciones/emprendimiento.png',
  },
  {
    id: 'galicia-enisa-startup',
    codigo: 'ENISA',
    nombre: 'ENISA Startup - Certificación de empresas emergentes',
    comunidad: 'galicia',
    categoria: 'emprendedores',
    organismo: 'ENISA - Ministerio de Industria',
    estado: 'abierta',
    plazoTexto: 'Convocatoria abierta todo el año',
    objeto: 'Certificación oficial de empresas emergentes para acceder a beneficios fiscales y financieros',
    beneficiarios: 'Empresas emergentes e innovadoras de cualquier sector.',
    imagen: '/images/subvenciones/enisa.jpg',
  },
  {
    id: 'galicia-pyme-innova-procesos-ig408l',
    codigo: 'IG408L',
    nombre: 'Pyme Innova - Procesos y Organización',
    comunidad: 'galicia',
    categoria: 'innovacion',
    organismo: 'IGAPE - Xunta de Galicia',
    estado: 'abierta',
    plazoInicio: '17 de enero de 2026',
    plazoFin: '17 de febrero de 2026',
    plazoTexto: 'Desde el 17 de enero al 17 de febrero de 2026',
    objeto: 'Apoyar proyectos de innovación en procesos y organización empresarial',
    beneficiarios: 'Pymes con sede social o centro de trabajo en Galicia.',
    imagen: '/images/subvenciones/innovacion-igape.png',
    destacada: true,
  },
  {
    id: 'galicia-pyme-innova-diseno-ig408l-2',
    codigo: 'IG408L-D',
    nombre: 'Pyme Innova - Diseño e Innovación',
    comunidad: 'galicia',
    categoria: 'innovacion',
    organismo: 'IGAPE - Xunta de Galicia',
    estado: 'abierta',
    plazoInicio: '17 de enero de 2026',
    plazoFin: '17 de febrero de 2026',
    plazoTexto: 'Desde el 17 de enero al 17 de febrero de 2026',
    objeto: 'Apoyar proyectos de innovación mediante diseño industrial y de producto',
    beneficiarios: 'Pymes con sede social o centro de trabajo en Galicia.',
    imagen: '/images/subvenciones/innovacion-igape.png',
  },
  {
    id: 'galicia-industria-innova-ig530b',
    codigo: 'IG530B',
    nombre: 'Industria Innova',
    comunidad: 'galicia',
    categoria: 'innovacion',
    organismo: 'IGAPE - Xunta de Galicia',
    estado: 'abierta',
    plazoInicio: '17 de enero de 2026',
    plazoFin: '17 de marzo de 2026',
    plazoTexto: 'Desde el 17 de enero al 17 de marzo de 2026',
    objeto: 'Apoyar el desarrollo de innovación industrial en empresas gallegas',
    beneficiarios: 'Empresas industriales con sede social o centro de trabajo en Galicia.',
    imagen: '/images/subvenciones/innovacion-igape.png',
  },
  {
    id: 'galicia-pyme-innova-camaras',
    codigo: 'INNCAM26',
    nombre: 'PYME Innova Cámaras',
    comunidad: 'galicia',
    categoria: 'innovacion',
    organismo: 'Cámaras de Comercio de Galicia',
    estado: 'proxima',
    plazoTexto: 'Convocatoria prevista para el segundo trimestre de 2026',
    objeto: 'Apoyar la innovación en gestión y desarrollo de producto a través de las Cámaras de Comercio',
    beneficiarios: 'Pymes con sede social o centro de trabajo en Galicia.',
    imagen: '/images/subvenciones/innovacion-igape.png',
  },
  {
    id: 'galicia-ticket-innova-ig408k',
    codigo: 'IG408K',
    nombre: 'Ticket Innova IGAPE',
    comunidad: 'galicia',
    categoria: 'innovacion',
    organismo: 'IGAPE - Xunta de Galicia',
    estado: 'abierta',
    plazoInicio: '26 de enero de 2026',
    plazoFin: '30 de septiembre de 2026',
    plazoTexto: 'Desde el 26 de enero al 30 de septiembre de 2026',
    objeto: 'Financiar servicios de innovación tecnológica y asesoramiento especializado',
    beneficiarios: 'Pymes con sede social o centro de trabajo en Galicia.',
    imagen: '/images/subvenciones/innovacion-igape.png',
  },
  {
    id: 'galicia-exporta-empresas-ig622a',
    codigo: 'IG622A',
    nombre: 'Galicia Exporta Empresas',
    comunidad: 'galicia',
    categoria: 'internacionalizacion',
    organismo: 'IGAPE - Xunta de Galicia',
    estado: 'abierta',
    plazoInicio: '28 de enero de 2026',
    plazoFin: '30 de septiembre de 2026',
    plazoTexto: 'Desde el 28 de enero al 30 de septiembre de 2026',
    objeto: 'Apoyar la participación de empresas gallegas en ferias y eventos internacionales',
    beneficiarios: 'Pymes gallegas con actividad exportadora o potencial exportador.',
    imagen: '/images/subvenciones/internacional.png',
  },
  {
    id: 'galicia-crece-cofides',
    codigo: 'COFIDES',
    nombre: 'CRECE + COFIDES',
    comunidad: 'galicia',
    categoria: 'internacionalizacion',
    organismo: 'COFIDES',
    estado: 'abierta',
    plazoTexto: 'Convocatoria abierta todo el año',
    objeto: 'Financiar inversiones de empresas españolas en países emergentes y en desarrollo',
    beneficiarios: 'Empresas españolas con proyectos de inversión internacional.',
    imagen: '/images/subvenciones/internacional.png',
  },
  {
    id: 'galicia-pyme-invierte',
    codigo: 'PYMINV',
    nombre: 'PYME Invierte',
    comunidad: 'galicia',
    categoria: 'internacionalizacion',
    organismo: 'ICEX / COFIDES',
    estado: 'abierta',
    plazoTexto: 'Convocatoria abierta todo el año',
    objeto: 'Financiar proyectos de internacionalización y expansión exterior de pymes',
    beneficiarios: 'Pymes españolas con proyectos de internacionalización.',
    imagen: '/images/subvenciones/internacional.png',
  },
  {
    id: 'galicia-bono-autonomos-tr341q',
    codigo: 'TR341Q',
    nombre: 'Bono Personas Autónomas',
    comunidad: 'galicia',
    categoria: 'inversion',
    organismo: 'Xunta de Galicia - Consellería de Emprego',
    estado: 'abierta',
    plazoInicio: '11 de febrero de 2026',
    plazoFin: '30 de septiembre de 2026',
    plazoTexto: 'Desde el 11 de febrero al 30 de septiembre de 2026',
    objeto: 'Financiar inversiones en digitalización, equipos y mejoras para autónomos',
    beneficiarios: 'Personas trabajadoras autónomas con domicilio fiscal en Galicia.',
    imagen: '/images/subvenciones/contratacion-autonomos.png',
  },
  {
    id: 'galicia-leader-mr701l',
    codigo: 'MR701L',
    nombre: 'Ayudas LEADER GDR',
    comunidad: 'galicia',
    categoria: 'inversion',
    organismo: 'Grupos de Desarrollo Rural - Xunta de Galicia',
    estado: 'abierta',
    plazoInicio: '3 de febrero de 2026',
    plazoFin: '6 de abril de 2026',
    plazoTexto: 'Desde el 3 de febrero al 6 de abril de 2026',
    objeto: 'Financiar infraestructuras y proyectos empresariales en zonas rurales',
    beneficiarios: 'Empresas y entidades ubicadas en zonas rurales elegibles de Galicia.',
    imagen: '/images/subvenciones/emprendimiento.png',
  },
  {
    id: 'galicia-transicion-justa-ig408n',
    codigo: 'IG408N',
    nombre: 'Fondo Transición Justa',
    comunidad: 'galicia',
    categoria: 'inversion',
    organismo: 'IGAPE - Xunta de Galicia',
    estado: 'abierta',
    plazoInicio: '31 de enero de 2026',
    plazoFin: '30 de abril de 2026',
    plazoTexto: 'Desde el 31 de enero al 30 de abril de 2026',
    objeto: 'Apoyar proyectos de descarbonización y transición ecológica industrial',
    beneficiarios: 'Empresas industriales de las zonas de transición justa en Galicia.',
    imagen: '/images/subvenciones/energia.png',
  },
  {
    id: 'galicia-estaciones-servicio-in519f',
    codigo: 'IN519F',
    nombre: 'Estaciones de Servicio Rurales',
    comunidad: 'galicia',
    categoria: 'inversion',
    organismo: 'Xunta de Galicia',
    estado: 'abierta',
    plazoInicio: '24 de enero de 2026',
    plazoFin: '9 de marzo de 2026',
    plazoTexto: 'Desde el 24 de enero al 9 de marzo de 2026',
    objeto: 'Modernización digital de estaciones de servicio en zonas rurales',
    beneficiarios: 'Estaciones de servicio ubicadas en zonas rurales de Galicia.',
    imagen: '/images/subvenciones/energia.png',
  },
  {
    id: 'galicia-fotovoltaica-in421s',
    codigo: 'IN421S',
    nombre: 'Energía Fotovoltaica',
    comunidad: 'galicia',
    categoria: 'inversion',
    organismo: 'Xunta de Galicia - INEGA',
    estado: 'abierta',
    plazoInicio: '28 de enero de 2026',
    plazoFin: '2 de marzo de 2026',
    plazoTexto: 'Desde el 28 de enero al 2 de marzo de 2026',
    objeto: 'Instalación de paneles solares fotovoltaicos y sistemas de almacenamiento',
    beneficiarios: 'Empresas, autónomos y entidades con sede en Galicia.',
    imagen: '/images/subvenciones/energia.png',
    destacada: true,
  },
  {
    id: 'galicia-eficiencia-energetica-in417y',
    codigo: 'IN417Y',
    nombre: 'Eficiencia Energética',
    comunidad: 'galicia',
    categoria: 'inversion',
    organismo: 'Xunta de Galicia - INEGA',
    estado: 'abierta',
    plazoInicio: '30 de enero de 2026',
    plazoFin: '15 de septiembre de 2026',
    plazoTexto: 'Desde el 30 de enero al 15 de septiembre de 2026',
    objeto: 'Proyectos de ahorro y eficiencia energética en empresas',
    beneficiarios: 'Empresas, autónomos y entidades con sede en Galicia.',
    imagen: '/images/subvenciones/energia.png',
  },
];

// Crear directorio si no existe
const outputDir = join(__dirname, '..', 'src', 'content', 'subvenciones');
try {
  mkdirSync(outputDir, { recursive: true });
} catch (e) {}

// Escribir cada subvención como archivo JSON
subvenciones.forEach(sub => {
  const filename = `${sub.comunidad}-${sub.codigo.toLowerCase()}.json`;
  const filepath = join(outputDir, filename);
  writeFileSync(filepath, JSON.stringify(sub, null, 2), 'utf-8');
  console.log(`Created: ${filename}`);
});

console.log(`\nTotal: ${subvenciones.length} subvenciones exportadas`);
